# -*- makefile -*- Time-stamp: <04/10/17 21:16:38 ptr>
# $Id: Makefile.inc,v 1.2 2008-02-26 14:59:44 bazis Exp $

PRGNAME = compiler_test
SRC_CPP = ttei1.cpp ttei2.cpp ttei3.cpp ttei4.cpp ttei5.cpp ttei6.cpp ttei7.cpp \
          movable.cpp
SRC_CC = eh.cc
