#pragma once
#define VIRTUALKD_VERSION 		2019,4
#define VIRTUALKD_VERSION_STR 	"2019.4"
#define COPYRIGHT_STR			"LGPL"
#define TRADEMARKS_STR			"VirtualKD-Redux"
#define PRODUCTNAME_STR			"VirtualKD-Redux"
#define COMPANY_STR				"VirtualKD-Redux"
#define COMMENTS_STR			"https://github.com/4d61726b/VirtualKD-Redux"
#define VIRTUALKD_VER_INT		0x7e300004

#define KDCLIENT_DLL_VER_STR	VIRTUALKD_VERSION_STR
#define KDCLIENT_DLL_VER		VIRTUALKD_VERSION

#define VMXPATCH_EXE_VER_STR	VIRTUALKD_VERSION_STR
#define VMXPATCH_EXE_VER		VIRTUALKD_VERSION

#define VMMON_EXE_VER_STR		VIRTUALKD_VERSION_STR
#define VMMON_EXE_VER			VIRTUALKD_VERSION

#define VMINSTALL_EXE_VER_STR	VIRTUALKD_VERSION_STR
#define VMINSTALL_EXE_VER		VIRTUALKD_VERSION

#define KERNEL_PART_VER			2019,4
#define KERNEL_PART_VER_STR		"2019.4"

#define KDPATCH_SYS_VER_STR		KERNEL_PART_VER_STR
#define KDPATCH_SYS_VER			KERNEL_PART_VER

#define KDVM_DLL_VER_STR		KERNEL_PART_VER_STR
#define KDVM_DLL_VER			KERNEL_PART_VER
